### ISSUE TITLE
Adapt dgtdriver for broadcast lichess

### ISSUE THREAD

**Issue by marciusbrandao** [arnsholt/dgtpgn#1]
....

**Comment by marciusbrandao** [comment]
Hi, I have 2 dgt boards and I want to use the dgtdriver to broadcast for lichess.
I downloaded dgtprn, but I don't know how to use it.


dgtpgn --debug --port COM7
Connecting to COM7
Starting read loop, outputPrefix=2021-09-16-141609

and now?

ps: I'm brazilian, sorry for my bad english.

**Comment by marciusbrandao** [comment]
After a game:
Got game, writing to 2021-09-16-145004-1.pgn

When restarting a new game:
Exception in thread "main" java.lang.RuntimeException: Piece removed from empty square.
	at org.riisholt.dgtdriver.moveparser.MoveParser.gotMessage(MoveParser.java:105)
	at org.riisholt.dgtpgn.DgtPgn.gotMessage(DgtPgn.java:54)
	at org.riisholt.dgtdriver.DgtDriver.tryEmitMessage(DgtDriver.java:402)
	at org.riisholt.dgtdriver.DgtDriver.gotBytes(DgtDriver.java:293)
	at org.riisholt.dgtpgn.Program.run(Program.java:79)
	at org.riisholt.dgtpgn.DgtPgn.main(DgtPgn.java:33)
Command execution failed.
